#!/bin/bash

# Make sure all the correct PPAs exist for extra apt packages.
apt_ppas() {

    if ! apt_repo_exists 'cassou'; then
        printf "Adding Cassou Repo for Emacs 24 Goodness\n"
        sudo apt-add-repository ppa:cassou/emacs -y
    fi

    if ! apt_repo_exists 'google'; then
        printf "Adding Google repo for Chrome\n"
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    fi

    if ! apt_repo_exists 'synapse'; then
        printf "Adding Synapse Launcher repo\n"
        sudo apt-add-repository ppa:synapse-core/ppa -y
    fi
}


# Make sure a list of key apt packages are all installed.
apt_install_standards() {



    local list_of_packages
    local -a missing_packages
    local -a packages_to_get=(
        'aptitude'
        'mysql-client'
        'mysql-server'
        'libmysqlclient-dev'
        'python-setuptools'
        'synapse'
        'texlive-full'
        'google-chrome-stable'
        'rails'
        'ruby1.9.3'
        'scala'
        'scala-doc'
        'mercurial'
        'linux-headers-generic'
    )

    for index in ${!packages_to_get[*]}
    do
        if ! package_installed ${packages_to_get[$index]}; then
            missing_packages=("${missing_packages[@]}" "${packages_to_get[$index]}")
        fi
    done

    if [[ "$missing_packages" ]]; then
        # Convert list to space-delimited string
        list_of_packages=$( printf "%s " "${missing_packages[@]}" )

        e_header "Installing missing packages"

        sudo apt-get install --install-suggests -f -y $list_of_packages

        [[ $? ]] && e_success "Done"

    fi

    if ! package_installed emacs24; then
        sudo apt-get purge emacs-snapshot-common emacs-snapshot-bin-common emacs-snapshot emacs-snapshot-el emacs-snapshot-gtk emacs23 emacs23-bin-common emacs23-common emacs23-el emacs23-nox emacs23-lucid auctex emacs24 emacs24-bin-common emacs24-common emacs24-common-non-dfsg
        sudo apt-get install -f -y  emacs24 emacs24-el emacs24-common-non-dfsg
    fi

}
