#!/bin/bash

install_emacs() {
    if ! formula_exists "emacs-mac"
    then

        brew install emacs-mac --with-modern-icon --with-imagemagick
        ln -sf /usr/local/opt/emacs-mac/Emacs.app /Applications
        EMACS=$(which emacs) brew install mu --with-emacs
    fi
}

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Updating Homebrew..."
        # Use the latest version of Homebrew
        brew update
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade
        [[ $? ]] && e_success "Done"

        e_header "Checking status of desired Homebrew formulae..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'ack'
            'aspell --with-lang=en'
            'bash'
            'bash-completion'
            'coreutils' # GNU core utilities (those that come with OS X are outdated)
            'ctags'
            'editorconfig'
            'forge'
            'freetype' # For matplotlib
            'gcc' # Theoretically subsumes gfortran
            'git'
            'global --with-exuberant-ctags'
            'htop'
            'imagemagick'
            'isync'
            'jpeg'
            'jq'
            'leiningen'
            'maven'
            'mercurial'
            'mono'
            'npm'
            'optipng'
            'pandoc'
            'pyqt' # Interactive pseudo-terminal
            'python'
            'rsync'
            'sbt'
            'scala'
            'the_silver_searcher'
            'tree'
            'wget'
            'zmq' # For IPython
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
            fi
        done

        if [[ "$missing_formulae" ]]; then
            # Convert the array of missing formula into a list of space-separate strings
            list_formulae=$( printf "%s " "${missing_formulae[@]}" )

            e_header "Installing missing Homebrew formulae..."
            # Install all missing formulae
            brew install $list_formulae

            [[ $? ]] && e_success "Done"
        fi

        install_emacs

        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit
    fi

}
