#!/bin/bash

# Make sure a list of key apt packages are all installed.
dnf_install_standards() {

    local list_of_packages
    local -a missing_packages

    local -a packages_to_get=(
        'emacs'
        'git'
    )

    for index in ${!packages_to_get[*]}
    do
        if ! package_installed ${packages_to_get[$index]}; then
            missing_packages=("${missing_packages[@]}" "${packages_to_get[$index]}")
        fi
    done

    if [[ "$missing_packages" ]]; then
        # Convert list to space-delimited string
        list_of_packages=$( printf "%s " "${missing_packages[@]}" )

        e_header "Installing missing packages"

        sudo apt-get install --install-suggests -fym $list_of_packages

        [[ $? ]] && e_success "Done"

    fi

}
