#!/bin/bash

run_pip() {

    # Make sure we're using a recent version of pip

    if on_deb && ! package_installed pip; then
        curl -fsSL https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python
    fi

    local -a desired_pip_packages=(
        'virtualenv'
        'virtualenvwrapper'
        'httpie'
        'pygments'
    )

    for index in ${!desired_pip_packages[*]}
    do
        if ! pip_package_installed ${desired_pip_packages[index]}; then
            sudo pip install ${desired_pip_packages[index]}
        else
            printf "Pip package already installed: %s\n" "${desired_pip_packages[index]}"
        fi
    done

    unset desired_pip_packages

}
