#!/bin/bash

run_pip() {

    # Make sure we're using a recent version of pip

    if [[ on_deb && ! "$(pip list)" ]]; then
        printf "Updating pip"
        curl -fsSL https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python
    fi

    local -a desired_pip_packages=(
        'distribute --upgrade'
        'pyflakes'
        'virtualenv'
        'virtualenvwrapper'
        'httpie'
        'Pygments'
    )

    # OSX Needs certain pip packages Debian can get from apt
    if [[ on_osx ]]; then
        desired_pip_packages+=(
            'scipy'
            'matplotlib'
            'pyzmq'
            'readline'
            'ipython'
            'pandas'
            'jinja2'
        )
    fi

    for index in ${!desired_pip_packages[*]}
    do
        if ! pip_package_installed ${desired_pip_packages[index]}; then
            sudo pip install ${desired_pip_packages[index]}
        fi
    done

    unset desired_pip_packages

}
