#!/bin/bash

# bash_profile

source "${HOME}/.dotfiles/lib/utils"

declare -a files=(
    $HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
    $HOME/.dotfiles/bash/bash_options # Options
    $HOME/.dotfiles/bash/bash_exports # Exports
    $HOME/.dotfiles/bash/bash_aliases # Aliases
    $HOME/.dotfiles/bash/functions/* # Functions
    $HOME/.dotfiles/bash/bash_prompt # Custom bash prompt
    $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    $HOME/.dotfiles/bash/bash_paths # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

# Check for a non-version-controlled alias file.
UNVCED_ALIASES=$HOME/.bash_local_only

if [[ -e ${UNVCED_ALIASES} ]]; then
    source ${UNVCED_ALIASES}
fi

unset files

# Only use `brew` after it has been added to the PATH
if on_osx; then
    bash_completion_path="$(brew --prefix)/etc/bash_completion"
fi

# Source OS defaults for things like colors, autocompletion
if on_deb; then
    source /etc/bashrc
fi

# Source Bash completion (installed via Homebrew)
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi

# Source virtualenvwrapper script. Maybe make this do location more sensibly?
venv_wrapper_script="/usr/local/bin/virtualenvwrapper.sh"
if [[ -r $venv_wrapper_script ]]; then
    source $venv_wrapper_script
fi
